language: ruby
rvm:
 - 2.4.4
dist: trusty
sudo: required

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_script:
  - mysql -e 'create database progress_dashboard_test'
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

script:
  - bundle exec rspec spec/
